version: "3.8"

services:
    postgres:
        image: postgres:11-alpine
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
            - POSTGRES_DB=db
    
    stripe_webhook:
        image: stripe/stripe-cli
        container_name: stripe_webhook
        command: listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to 172.17.0.1:8080/stripe-webhook

    app:
        image: monkeybase
        container_name: app
        build:
            context: backend
            dockerfile: ./Dockerfile
        ports:
            - 8080:80
        environment:
            - PROJECT_NAME=monkeybase
            - POSTGRES_SERVER=postgres
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
            - POSTGRES_DB=db
            - BACKEND_CORS_ORIGINS=["http://localhost","http://localhost:8080"]
            - SERVER_HOST=http://localhost
            - SECRET_KEY=UNSAFE_SET_THIS!