FROM python:3.8
# need the full version as some precompiled wheels are missing for raspberry 

RUN pip install --no-cache-dir "uvicorn[standard]" gunicorn fastapi

COPY ./gunicorn_conf.py /gunicorn_conf.py

COPY ./start-reload.sh /start-reload.sh
RUN chmod +x /start-reload.sh

COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend /backend

WORKDIR /backend

ENV PYTHONPATH=/backend

EXPOSE 80

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Uvicorn
CMD ["/start-reload.sh"]