name: monkeybase backend

on:
  push:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"

env:
  PROJECT_NAME: testing
  POSTGRES_SERVER: localhost
  POSTGRES_USER: db_user
  POSTGRES_PASSWORD: db_pass
  POSTGRES_DB: db
  SERVER_HOST: http://localhost
  SECRET_KEY: secret-key-for-testing

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_pass
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
      working-directory: backend
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: backend
    - name: seed data
      run: |
        python -m app.seed
      working-directory: backend/app
    - name: Test with pytest
      run: |
        pytest
      working-directory: backend
